# Generated by Django 5.2.4 on 2025-07-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('Sale', 'For Sale'), ('Rent', 'For Rent')], max_length=10)),
                ('image', models.URLField()),
                ('description', models.TextField()),
            ],
        ),
    ]
